@resources-service = localhost:5000
@resource-id = 740f3d2f-2eb2-50e4-b695-aeed86dfe674

### Update Resource
POST http://{{resources-service}}/api/resources
Content-Type: application/json

{"id":"740f3d2f-2eb2-50e4-b695-aeed86dfe674","display":"Azure service updates","statusCode":200,"created":"2020-06-23T03:48:02.2274477+00:00","isActive":true,"type":"page","description":"Azure service updates","self":"https://azure.microsoft.com/en-us/roadmap/feed/","published":"0001-01-01T00:00:00"}